services:
  web:
    networks:
      - default
      - coolify
    labels:
      traefik.enable: "true"
      traefik.docker.network: coolify
      traefik.http.middlewares.globortunity-gzip.compress: "true"
      traefik.http.routers.globortunity-http.entrypoints: http
      traefik.http.routers.globortunity-http.rule: "Host(`${APP_HOST:-47.109.60.123}`)"
      traefik.http.routers.globortunity-http.middlewares: globortunity-gzip
      traefik.http.routers.globortunity-http.service: globortunity-web
      traefik.http.services.globortunity-web.loadbalancer.server.port: "8080"

networks:
  coolify:
    external: true
