import type { NormalizedJobInput } from "@globortunity/domain";

const now = Date.now();

export const demoJobs: NormalizedJobInput[] = [
  {
    sourceId: "demo",
    externalId: "demo-001",
    sourceUrl: "https://example.com/jobs/demo-001",
    title: "Senior Frontend Engineer",
    companyName: "Northstar Labs",
    location: "China / Remote",
    description: "Build accessible React product surfaces for a distributed analytics team. You will own frontend architecture, performance, and design-system quality.",
    remoteScope: "remote",
    remoteConfidence: 0.98,
    employmentType: "full-time",
    salary: { min: 35_000, max: 50_000, currency: "CNY", period: "month", text: "CNY 35K-50K / month" },
    tags: ["React", "TypeScript", "Accessibility"],
    publishedAt: new Date(now - 2 * 60 * 60 * 1000),
    rawData: { demo: true },
  },
  {
    sourceId: "demo",
    externalId: "demo-002",
    sourceUrl: "https://example.com/jobs/demo-002",
    title: "Product Designer",
    companyName: "Lattice Works",
    location: "APAC / Remote",
    description: "Lead end-to-end product design for collaboration tools used by globally distributed operations teams.",
    remoteScope: "remote",
    remoteConfidence: 0.97,
    employmentType: "full-time",
    salary: { min: 30_000, max: 42_000, currency: "CNY", period: "month", text: "CNY 30K-42K / month" },
    tags: ["Product design", "Figma", "Research"],
    publishedAt: new Date(now - 5 * 60 * 60 * 1000),
    rawData: { demo: true },
  },
  {
    sourceId: "demo",
    externalId: "demo-003",
    sourceUrl: "https://example.com/jobs/demo-003",
    title: "Backend Platform Engineer",
    companyName: "Greenline Systems",
    location: "Shanghai / Hybrid",
    description: "Develop event-driven services and data pipelines for a high-volume logistics platform. Two office days per week.",
    remoteScope: "hybrid",
    remoteConfidence: 0.92,
    employmentType: "full-time",
    salary: { min: 38_000, max: 55_000, currency: "CNY", period: "month", text: "CNY 38K-55K / month" },
    tags: ["Node.js", "PostgreSQL", "Kafka"],
    publishedAt: new Date(now - 26 * 60 * 60 * 1000),
    rawData: { demo: true },
  },
  {
    sourceId: "demo",
    externalId: "demo-004",
    sourceUrl: "https://example.com/jobs/demo-004",
    title: "Developer Relations Lead",
    companyName: "Orbit Cloud",
    location: "Global / Remote",
    description: "Create technical content, grow an open-source community, and represent a developer infrastructure product across time zones.",
    remoteScope: "remote",
    remoteConfidence: 0.99,
    employmentType: "full-time",
    salary: { min: 105_000, max: 145_000, currency: "USD", period: "year", text: "USD 105K-145K / year" },
    tags: ["Open source", "Content", "Community"],
    publishedAt: new Date(now - 2 * 24 * 60 * 60 * 1000),
    rawData: { demo: true },
  },
  {
    sourceId: "demo",
    externalId: "demo-005",
    sourceUrl: "https://example.com/jobs/demo-005",
    title: "Data Analyst",
    companyName: "Mosaic Health",
    location: "China / Remote",
    description: "Partner with product and operations teams to define metrics, model datasets, and communicate actionable insights.",
    remoteScope: "remote",
    remoteConfidence: 0.96,
    employmentType: "contract",
    salary: { min: 240, max: 320, currency: "CNY", period: "hour", text: "CNY 240-320 / hour" },
    tags: ["SQL", "dbt", "Product analytics"],
    publishedAt: new Date(now - 3 * 24 * 60 * 60 * 1000),
    rawData: { demo: true },
  },
  {
    sourceId: "demo",
    externalId: "demo-006",
    sourceUrl: "https://example.com/jobs/demo-006",
    title: "Customer Success Manager",
    companyName: "Relay Commerce",
    location: "Shenzhen / Hybrid",
    description: "Guide enterprise customers through onboarding and adoption for a cross-border commerce platform.",
    remoteScope: "hybrid",
    remoteConfidence: 0.9,
    employmentType: "full-time",
    salary: { min: 24_000, max: 34_000, currency: "CNY", period: "month", text: "CNY 24K-34K / month" },
    tags: ["SaaS", "Enterprise", "Mandarin"],
    publishedAt: new Date(now - 4 * 24 * 60 * 60 * 1000),
    rawData: { demo: true },
  },
];
